### ISSUE TITLE
Adicionar COLLABCODE

### ISSUE THREAD

**Issue by SauloNunes** [Wmitrut/awesome-brazilian-devblogs#38]
Boa Tarde @Wmitrut 

estou montando uma call que vou apresentar amanhã sobre como contribuir em projetos open source, e gostaria de recomendar o seu repo como exemplo.

Gostaria de realizar um PR adicionado o [CollabCode](https://medium.com/collabcode) - Front-End, Back-End, Mobile, Javascript, Design e UX

Obrigado

**Comment by Wmitrut** [comment]
@SauloNunes Fica a vontade!! Me mande mais detalhes de horario e link também! Valeu!

**Comment by SauloNunes** [comment]
Perfeito.

vai ser pro pessoal da empresa aproximadamente as 09:15 da manhã. quando gerar o link do meets eu repasso.

**Comment by Wmitrut** [comment]
Se tiver link, pode me mandar, perdi a live mas to afim de ver!
